### ISSUE TITLE
JitPack Package

### ISSUE THREAD

**Issue by esetnik** [freefair/okhttp-spring-boot#4]
Using:

``` 
compile 'io.freefair.okhttp-spring-boot:okhttp3-spring-boot-starter:1.1.0'
```

results in:

```
org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$ArtifactResolveException: Could not resolve all files for configuration ':compileClasspath'.
Caused by: org.gradle.internal.resolve.ArtifactNotFoundException: Could not find okhttp3-spring-boot-starter.jar (io.freefair.okhttp-spring-boot:okhttp3-spring-boot-starter:1.1.0).
Searched in the following locations:
    https://jitpack.io/io/freefair/okhttp-spring-boot/okhttp3-spring-boot-starter/1.1.0/okhttp3-spring-boot-starter-1.1.0.jar
```

It looks like the `JitPack` url at `https://jitpack.io/#io.freefair/okhttp-spring-boot/1.1.0` is recommending:

```
compile 'io.freefair.okhttp-spring-boot:okhttp-spring-boot-autoconfigure:1.1.0'
```

**Comment by esetnik** [comment]
It looks like the actual jars are missing from JitPack.

`https://jitpack.io/io/freefair/okhttp-spring-boot/okhttp3-spring-boot-starter/1.1.0/okhttp3-spring-boot-starter-1.1.0.jar` is a 404

**Comment by larsgrefer** [comment]
@esetnik Please try again with version `1.1.1`

The `starter`-projects do not contain any code. Their only purpose is to declare dependencies on `io.freefair.okhttp-spring-boot:okhttp-spring-boot-autoconfigure` and okhttp. (see http://docs.spring.io/spring-boot/docs/1.5.2.RELEASE/reference/htmlsingle/#boot-features-custom-starter-module-starter).
For some reason the empty jar wasn't added to the `archives` configuration of my gradle build and thus not published to/by Jitpack

>It looks like the JitPack url at `https://jitpack.io/#io.freefair/okhttp-spring-boot/1.1.0` is recommending:
`compile 'io.freefair.okhttp-spring-boot:okhttp-spring-boot-autoconfigure:1.1.0'`

This is only the case because it's the alphabetical first module. On the right side you can see a dropdown with all modules.
![bildschirmfoto 2017-03-08 um 01 36 05](https://cloud.githubusercontent.com/assets/6069961/23684549/ad915a94-039f-11e7-9f7a-83e6d041eb04.png)

**Comment by esetnik** [comment]
Confirmed `1.1.1` is working perfectly. Thanks :)

**Comment by larsgrefer** [comment]
You're welcome.

Thanks for the confirmation
